config/routes.rb
Rails.application.routes.draw do

  #attachinary setup
  mount Attachinary::Engine => "/attachinary"



  get 'leads/new'

  get 'leads/create'

  ActiveAdmin.routes(self)
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations" }
  root to: 'pages#home'

  get 'messages/:id/create', to: 'messages#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # routes for leads
  resources :leads, only: [:new, :create, :show]

  #routes for users
  resources :users, only: [:edit, :update]



  #routes for interviews
  resources :interviews, only: [:show, :new, :create, :edit, :update, :found_apartment]

  post 'interviews/:id/found_apartment', to: 'interviews#found_apartment'
  get 'interviews/:id/edit_later', to: 'interviews#edit_later', as: :edit_later
  post 'interviews/:id/create_pdf', to: 'interviews#create_pdf', as: :create_pdf
  post 'interviews/:id', to: 'users#update_later', as: :update_user

  #routes for content pages: team, contact
  get 'team', to: 'pages#team'
  get 'contact', to: 'pages#contact'

  #routes for organisations
  resources :organisations, only: [:index, :show, :new, :create, :edit, :update]

end

app/models/organisation.rb
class Organisation < ApplicationRecord
  has_many :users
  has_many :interviews
  validates :name, presence: true
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :set_organisation
  before_action :get_current_user, only: [:create, :update]

  def index
    @organisations = policy_scope(Organisation)
    @interviews = helpers.fetch_interviews(params[:tab])
    @user = current_user
  end

  def show
    @interview = Interview.find(params[:id])
    @student = @interview.user
    unless OrganisationPolicy.new(current_user, @organisation, @student).show?
      raise Pundit::NotAuthorizedError
    end
    @messages = Message.where({sender_id: @student.id}).or(Message.where({receiver_id: @student.id}))
    skip_authorization
  end

  def create
  end

  def destroy
  end

  def edit
    @interview = Interview.find(params[:id])
    @student = @interview.user
    if @interview.organisation == current_user.organisation && params[:field].present?
      @interview[params[:field]] = !@interview[params[:field]]
      @interview.save!
    end
    skip_authorization
  end

  def update
  end

  def new
  end

  private

  def get_current_user
    @user = current_user
  end

  def set_organisation
    @organisation = current_user.organisation
  end
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
  def fetch_interviews(id)
    id = id.to_i
    case id
      when 1
        interviews = Interview.where({ organisation_id: current_user.organisation.id })
      when 2
        interviews = Interview.where({
          organisation_id: current_user.organisation.id,
          interview_completed: false,
          documents_submitted: false,
          documents_validated: false,
          agreement_signed: false,
          lease_provided: false,
          lease_signed: false
        })
      when 3
        interviews = Interview.where({
          organisation_id: current_user.organisation.id,
          interview_completed: true,
          documents_submitted: true,
          documents_validated: false,
          agreement_signed: false,
          lease_provided: false,
          lease_signed: false
        })
      when 4
        interviews = Interview.where({
          organisation_id: current_user.organisation.id,
          interview_completed: true,
          documents_submitted: true,
          documents_validated: true,
          agreement_signed: true,
          lease_provided: false,
          lease_signed: false
        })
      when 5
        interviews = Interview.where({ organisation_id: current_user.organisation.id })
      else
        interviews = Interview.where({ organisation_id: current_user.organisation.id })
      end
  end

  def active_feature?(instance, field)
    if field == "documents_submitted"
      (instance.id_card && instance.school_certificate && instance.proof_of_revenue) ? "active-feature" : ""
    else
      instance[field] ? "active-feature" : ""
    end
  end

  def compute_student_stage(student)
    fields = [
      "professional_status",
      "city",
      "move_in_date",
      "monthly_budget",
      "monthly_income",
      "unique_signator",
      "organisation_id"
    ]
    score = 0
    interview = student.interviews.last
    fields.each do |field|
      score += 0.1 unless interview[field].nil?
    end
    score += 0.1 unless interview.id_card.present?
    score += 0.1 unless interview.proof_of_revenue.present?
    score += 0.1 unless interview.school_certificate.present?
    return score
  end
end

app/views/organisations/_certification_requirements.html.erb
<div class="dashboard-user-card">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="requirements-title-container">
          <h4>Certification requirements</h4>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-4">
        <div class="dashboard-user-feature">
          <div id="interview_completed" class="dashboard-user-feature-icon-container <%= active_feature?(@interview, "interview_completed") %>">
            <%= image_tag "typewriter.png", class: "dashboard-user-feature-icon", id: "interview_completed" %>
          </div>
          <div class="dashboard-user-feature-text">
            <span>Application Completed</span>
          </div>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="dashboard-user-feature">
          <div id="documents_submitted" class="dashboard-user-feature-icon-container  <%= active_feature?(@interview, "documents_submitted")%>">
            <%= image_tag "folder.png", class: "dashboard-user-feature-icon", id: "documents_submitted" %>
          </div>
          <div class="dashboard-user-feature-text">
            <span>Documents submitted</span>
          </div>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="dashboard-user-feature">
          <div id="documents_validated" class="dashboard-user-feature-icon-container activable-feature <%= active_feature?(@interview, "documents_validated")%>">
            <%= image_tag "diploma.png", class: "dashboard-user-feature-icon", id: "documents_validated" %>
          </div>
          <div class="dashboard-user-feature-text">
            <span>Documents validated</span>
          </div>
        </div>
      </div>

    </div>
    <div class="row">
      <div class="col-xs-4">
        <div class="dashboard-user-feature">
          <div id="agreement_signed" class="dashboard-user-feature-icon-container activable-feature <%= active_feature?(@interview, "agreement_signed")%>">
            <%= image_tag "agreement.png", class: "dashboard-user-feature-icon", id: "agreement_signed" %>
          </div>
          <div class="dashboard-user-feature-text">
            <span>G. Agreement signed</span>
          </div>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="dashboard-user-feature">
          <div id="lease_provided" class="dashboard-user-feature-icon-container activable-feature <%= active_feature?(@interview, "lease_provided")%>">
            <%= image_tag "court.png", class: "dashboard-user-feature-icon", id: "lease_provided" %>
          </div>
          <div class="dashboard-user-feature-text">
            <span>Lease provided</span>
          </div>
        </div>
      </div>
      <div class="col-xs-4">
        <div class="dashboard-user-feature">
          <div id="lease_signed" class="dashboard-user-feature-icon-container activable-feature <%= active_feature?(@interview, "lease_signed")%>">
            <%= image_tag "act.png", class: "dashboard-user-feature-icon", id: "lease_signed" %>
          </div>
          <div class="dashboard-user-feature-text">
            <span>Lease signed</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/organisations/_chat.html.erb
<div class="dashboard-user-card">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="requirements-title-container">
          <h4>Conversation</h4>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">

        <div class="messages-container" id="m-container">
          <% @messages.each do |message|%>
            <div class="message">
              <p class="message-sender"><%= message.sender.first_name %> <%= message.sender.last_name %></p>
              <p class="message-timestamp"><%= message.created_at %></p>
              <p class="message-content"><%= message.content %></p>
            </div>
          <% end %>
        </div>
        <div class="message-form-container">
          <form class="message-form" action="/">
            <div class="form-group">
              <textarea class="form-control" id="message-area" rows="3"></textarea>
            </div>
             <div class="submit-container">
                <i class="fa fa-send"></i><input type="submit" value="Send Message"></input>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/organisations/_user_card.html.erb
<div class="dashboard-user-card">
  <div class="dashboard-user-card-left">
    <%= user_picture_avatar(@student, "avatar-bordered-xl")  %>
    <h5><%= @student.first_name.capitalize %> <%= @student.last_name.capitalize %></h5>
    <p><%= @student.organisation.name.upcase %></p>
    <%= link_to "See Documents", interview_path(@interview, format: :pdf), method: :get, class: "btn btn-primary btn-xs", style: "padding: 8px" %>
  </div>

  <div class="dashboard-user-card-separator">

  </div>
  <div class="dashboard-user-card-right">

    <div class="dashboard-user-card-right-item">
      <div class="dashboard-user-card-right-item-icon">
        <i class="fa fa-check-circle-o"></i>
      </div>
      <div class="dashboard-user-card-right-item-text">
      <span class="dashboard-user-card-right-item-text-title">Co-Signer</span>
        <% if @interview.has_a_cosigner == true %>
          <p>Has a co-signer</p>
        <% else %>
          <p>Does not have a co-signer</p>
        <% end %>

      </div>
    </div>

    <div class="dashboard-user-card-right-item">
      <div class="dashboard-user-card-right-item-icon">
        <i class="fa fa-calendar"></i>
      </div>
      <div class="dashboard-user-card-right-item-text">
      <span class="dashboard-user-card-right-item-text-title">Move-in Date</span>
      <p><%= @interview.move_in_date.present? ? @interview.move_in_date : '-' %></p>
      </div>
    </div>

    <div class="dashboard-user-card-right-item">
      <div class="dashboard-user-card-right-item-icon">
        <i class="fa fa-calculator"></i>
      </div>
      <div class="dashboard-user-card-right-item-text">
      <span class="dashboard-user-card-right-item-text-title">Budget</span>
      <p><%= @interview.monthly_budget.present? ? @interview.monthly_budget : '-' %> €</p>
      </div>
    </div>

    <div class="dashboard-user-card-right-item">
      <div class="dashboard-user-card-right-item-icon">
        <i class="fa fa-money"></i>
      </div>
      <div class="dashboard-user-card-right-item-text">
      <span class="dashboard-user-card-right-item-text-title">Revenue</span>
      <p><%= @interview.monthly_income.present? ? @interview.monthly_income : '-' %>  €</p>
      </div>
    </div>
  </div>
</div>

app/views/organisations/create.html.erb
<h1>Organisations#create</h1>
<p>Find me in app/views/organisations/create.html.erb</p>

app/views/organisations/destroy.html.erb
<h1>Organisations#destroy</h1>
<p>Find me in app/views/organisations/destroy.html.erb</p>

app/views/organisations/index.html.erb
<% content_for(:title_tag) do %>
  Manager view
<% end %>

<div class="container no-padding body-container-no-footer">
  <div class="header">
    <div class="profile">
      <div class="user-show-photo">
        <%= user_picture_avatar(current_user, "avatar organisation-avatar") %>
      </div>
      <h1><%= @user.first_name %>, Manager @Garantme</h1>
    </div>
    <div class="container-fluid no-padding">
      <div class="row">
        <div class="col-xs-12 col-md-8 col-md-offset-2 no-padding">
          <div class="tabs">
            <%= link_to "/organisations?tab=1", class: "tab first", id: "1" do %>
                <h3>All Profiles</h3>
            <%end%>
            <%= link_to "/organisations?tab=2", class: "tab", id: "2" do %>
                <h3>New Profiles</h3>
            <%end%>
            <%= link_to "/organisations?tab=3", class: "tab", id: "3" do %>
                <h3>Submitted Applications</h3>
            <%end%>
            <%= link_to "/organisations?tab=4", class: "tab", id: "4" do %>
                <h3>Certified Users</h3>
            <%end%>
            <%= link_to "/organisations?tab=5", class: "tab last", id: "5 last" do %>
                <h3>Expired Certifications</h3>
            <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container-fluid no-padding">
    <div class="row">
      <div class="col-xs-12 col-md-8 col-md-offset-2 no-padding">
        <div class="dashboard-container">
          <table id="dashboard-table" class="table table-hover" cellspacing="0"">
            <thead>
              <tr>
                <th>#</th>
                <th>User</th>
                <th>Stage</th>
                <th>Move-in date</th>
                <th>Status</th>
                <th></th>
              </tr>
            </thead>
            <tbody>

              <% @interviews.each_with_index do |itw, i| %>
                <tr>
                  <th scope="row"><%= i+1 %></th>
                  <td><%=  itw.user.first_name.capitalize %> <%= itw.user.last_name.capitalize %></td>
                  <td><%= (compute_student_stage(itw.user)*100).to_i %> %</td>
                  <td><%= itw.move_in_date.strftime("%F") unless itw.move_in_date.nil? %></td>
                  <td>Pending</td>
                  <td>
                    <%= link_to organisation_path(itw.id) do %>
                       <i class="fa fa-eye"></i>
                    <% end %>
                  </td>
                </tr>
              <%end%>

            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for(:js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      $('#dashboard-table').DataTable();
      $('#<%= params[:tab].nil? ? 1 : params[:tab]  %>').addClass('active');
    } );
  <% end %>
<% end %>

app/views/organisations/new.html.erb
<h1>Organisations#new</h1>
<p>Find me in app/views/organisations/new.html.erb</p>

app/views/organisations/show.html.erb
<div class="container-fluid body-container-spreader gray">

  <div class="row">
      <div class="container-fluid">
        <div class="row">
          <div class="col-xs-12 col-md-5 col-md-offset-1">
            <div class="row">
              <div class="col-xs-12">

                <%= render "user_card" %>

              </div>
            </div>
            <div class="row">
              <div class="col-xs-12">
                <div class="dashboard-user-card">
                  <div class="student-info-container">
                    <div class="phone_number">
                      <span><i class="fa fa-phone"></i><%= @student.phone_number.nil? ? "-" : @student.phone_number %> </span>
                    </div>
                    <div class="contact_mail">
                    <span><i class="fa fa-envelope"></i><%= @student.email %></span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-md-5">
            <div class="row">
              <div class="col-xs-12">

                <%= render "certification_requirements" %>

              </div>
            </div>
            <!-- commented after implementation of crisp -->
          <!--   <div class="row">
              <div class="col-xs-12">

                <%= render "chat" %>

              </div>
            </div> -->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for(:js) do %>
  <%= javascript_tag do %>
   function updateScroll(){
    var element = document.getElementById("m-container");
    element.scrollTop = element.scrollHeight;
    }

    $(document).ready(function() {
      $( ".activable-feature" ).click(function(e) {
        $(this).toggleClass( "active-feature" );
        var url = "/organisations/<%= @interview.id %>/edit?field=" + e.target.id
        $.ajax({
          type: "GET",
          url: url
        });
      });
      $('.message-form').submit(function(e) {
          e.preventDefault();
          var content = "<div class=\"message\"><p class=\"message-sender\"><%= current_user.first_name %> <%= current_user.last_name %></p><p class=\"message-timestamp\">A few seconds ago</p><p class=\"message-content\">" + $("#message-area").val() + "</p></div>"
          $( ".messages-container" ).append(content);
          var url = "/messages/<%= @interview.id %>/create?message=" + encodeURI($('#message-area').val())
          $('#message-area').val('');
        $.ajax({
          type: "GET",
          url: url
        });
        updateScroll()
      })
    });
  <% end %>
<% end %>

app/views/organisations/update.html.erb
<h1>Organisations#update</h1>
<p>Find me in app/views/organisations/update.html.erb</p>