config/routes.rb
Rails.application.routes.draw do

  #attachinary setup
  mount Attachinary::Engine => "/attachinary"



  get 'leads/new'

  get 'leads/create'

  ActiveAdmin.routes(self)
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations" }
  root to: 'pages#home'

  get 'messages/:id/create', to: 'messages#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # routes for leads
  resources :leads, only: [:new, :create, :show]

  #routes for users
  resources :users, only: [:edit, :update]



  #routes for interviews
  resources :interviews, only: [:show, :new, :create, :edit, :update, :found_apartment]

  post 'interviews/:id/found_apartment', to: 'interviews#found_apartment'
  get 'interviews/:id/edit_later', to: 'interviews#edit_later', as: :edit_later
  post 'interviews/:id/create_pdf', to: 'interviews#create_pdf', as: :create_pdf
  post 'interviews/:id', to: 'users#update_later', as: :update_user

  #routes for content pages: team, contact
  get 'team', to: 'pages#team'
  get 'contact', to: 'pages#contact'

  #routes for organisations
  resources :organisations, only: [:index, :show, :new, :create, :edit, :update]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">

  <div class="navbar-wagon-brand">
    <%= image_tag "Garantme-logo-white.png" %>
  </div>

  <div class="row">
    <div class="col-md-4 col-sm-6">
      <div class="social-media">
        <h5>CONNECT WITH US</h5>
        <ul class="social-icon">
          <%= link_to "https://www.facebook.com/garantme/" do %>
            <i class="fa fa-facebook-square"></i>
          <% end %>
        </ul>
        <ul class="social-icon">
          <p>contact@garantme.fr</p>
        </ul>
      </div>
    </div>
  </div>


</div>
<div class="copyright">
  <div class="row">
    <div class="col-md-4 col-sm-6">
      <h6>Copyright © 2017 Garantme, All rights reserved.</h6>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon <%= yield(:navbar_class) %>">
  <!-- Logo -->
  <div class="navbar-wagon-brand">
    <% if controller_name == "pages" && action_name == "home" %>
      <%= link_to root_path do %>
        <%= image_tag "Garantme-logo-white.png" %>
      <% end %>
    <% else %>
      <%= link_to root_path do %>
        <%= image_tag "Garantme-logo-black.png" %>
      <% end %>
    <% end %>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

  <!-- Text link -->
     <%= link_to "Contact", contact_path, class: "navbar-wagon-item navbar-wagon-link"  %>

    <!-- Text link -->
    <%= link_to "Team", team_path, class: "navbar-wagon-item navbar-wagon-link"  %>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <!-- to be linked with chat -->
          <!-- <div class="badge badge-green">3</div> -->
          <!-- to be linked with chat -->
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <div id="navbar-wagon-menu" data-toggle="dropdown">
            <%= user_picture_avatar(current_user, "avatar dropdown-toggle") %>
          </div>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <% if current_user.is_manager %>
              <li>
                <%= link_to organisations_path do %>
                  <i class="fa fa-tachometer"></i> <%= t(".dashboard", default: "Dashboard") %>
                <% end %>
              </li>
            <% end %>
            <% if user_signed_in? %>
              <% if current_user.interviews.empty? %>
                <li class ="profile-one <%= "hidden" if current_user.is_manager == true  %>">
                  <%= link_to new_interview_path do %>
                    <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to interview_path (current_user.interviews.last.id) do %>
                    <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                  <% end %>
                </li>
              <% end %>
            <% end %>
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-cog" ></i> <%= t(".profile", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <% if user_signed_in? %>
              <% if current_user.is_manager %>
                <li>
                  <%= link_to organisations_path do %>
                    <i class="fa fa-tachometer"></i> <%= t(".dashboard", default: "Dashboard") %>
                  <% end %>
                </li>
              <% end %>
            <% end %>
            <% if user_signed_in? %>
              <% if current_user.interviews.empty? %>
                <li class ="profile-one <%= "hidden" if current_user.is_manager == true  %>">
                  <%= link_to new_interview_path do %>
                    <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to interview_path (current_user.interviews.last.id) do %>
                    <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                  <% end %>
                </li>
              <% end %>
            <% end %>
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
      </ul>
    </div>
  </div>
</div>